language: go

go:
  - master
  - 1.9.x
  - 1.8.x

install:
  - go get -v -t ./...
  - go get github.com/onsi/gomega
  - go install github.com/onsi/ginkgo/ginkgo
  - export PATH=$PATH:$GOPATH/bin

script: ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --trace --race --compilers=2
